### ISSUE TITLE
Users flow

### ISSUE THREAD

**Issue by tcp** [OpenMined/pygrid-admin#14]
## Epic description
Build the flow for managing internal and external PyGrid users.

Basic Functionality
---
We have to hook the Domain API from PyGrid and support CRUD operations over users, groups and roles.

Since we have no pages in Framer for this section, I have listed all the actions the PyGrid Admin must support below:

_Users_
- [x] Create User
- [x] Get User
- [x] Get Users
- [x] Search Users
- [x] Change email
- [x] Change password
- [x] Change Role
- [x] Change Group
- [x] Delete user

_Groups_
- [x] Create Group
- [x] Get Group
- [x] Get Groups
- [x] Update Group
- [x] Delete Group

_Roles_
- [x] Create Role
- [x] Get Role
- [x] Get Roles
- [x] Update Role
- [x] Delete Role

User Interface
---
There are no designs for this section of the PyGrid Admin. Do the best you can:

_Users section_
- [x] #15 Show all users with pagination
- [x] #16 Modal for creating a new user
- [x] #17 Overview of current user account creation requests
- [x] #18 Overview of groups with links
- [x] #18 Overview of roles with links

_Group subsection_
- [x] #19 Show all groups with pagination
- [x] #20 Create a new group
- [x] #21 Edit, delete groups

_Roles subsection_
- [x] #22 Show all roles with pagination
- [x] #23 Create a new role
- [x] #24 Edit, delete roles

## Done
---
This Epic is complete when the User Interface issues are done.

**Comment by tcp** [comment]
Pagination > post release
